### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Lettuceleaff** [Fennecai/Aperture-Continued#12]
Would it be possible to add an item dropper in the pneumatic diversity vent category, where it would function as a normal item dropper but instead of dropping an item on its own, it would connect to the pneumatic diversity vent and drop whatever the vent brought into it?

**Comment by Fennecai** [comment]
Potentially.

I have it on my todo list; cause somebody else already suggested item droppers be connectable to the vents.

**Comment by Lettuceleaff** [comment]
Not any I can think of.

**Comment by Fennecai** [comment]
ok, cool.
