### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by guadalajara** [Fennecai/Aperture-Continued#13]
**Describe the bug**
If a pneumatic diversity vent leads back into itself, the item traveling inside, if it creates a complete loop in the vent, stops moving.

**To Reproduce**
1. Go to 'The Aperture tab'
2. Click on 'Diversity Vent'
3. Build a vent that has a T junction and makes a loop so it connects back to itself.
4. Send an item in the vent.
5. See error

**Expected behavior**
The pneumatic diversity vent continues to transport the item.

**Comment by Fennecai** [comment]
Very much aware of this issue; will try to fix in an update sometime in the future

**Comment by CrishNate** [comment]
Actually it can be easelly fixed

**Comment by Fennecai** [comment]
we have now "Easily" fixed the issue; after we worked on it for several days.
