### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by theepicbread** [Fennecai/Aperture-Continued#15]
**Is your feature request related to a problem? If so, Please describe.**
No.

**Describe the solution you'd like**
An opaque pnueumatic diversity vent tube such as the gel tubes in Portal 2.

**Describe alternatives you've considered**
None I can think of.
**Additional context**
None I can think of.

**Comment by Fennecai** [comment]
seems pretty simple to add. :)
already on my todo list!
