### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lettuceleaff** [Fennecai/Aperture-Continued#17]
**Describe the bug**
The adhesion gel doesn't make you stick to it, and the console says "Attempted to create unknown entity type aperture_player_avatar!" Occasionally you will but you appear to be very tall.

**To Reproduce**
1. Go to 'weapons'
2. Click on 'paint gun'
3. Switch down to 'adhesion gel'
4. Try to use adhesion gel
5. See error

**Expected behavior**
You walk on the wall where the adhesion gel is.
**Screenshots**
If applicable, add screenshots and/or video to help explain your problem.

**Additional context**
In the third person, it shows the avatar floating next to the adhesion gel if you do end up sticking to it.

**Comment by Fennecai** [comment]
Please see my comment on the other, Identical, bug that you posted.
