### ISSUE TITLE
[SUGGESTION] fx models, gib models, better and destroying thermal discouragement beams

### ISSUE THREAD

**Issue by DahMario** [Fennecai/Aperture-Continued#19]
i have a few suggestions:
1. make the discouragement beams break the breakable objects, but not glass because the beams go through glass in portal 2
2. make the discouragement beams destroy turrets, and maybe even have the turrets scream in pain like they do in the game
3. making the turret laser turret gibs in the files of portal 2 appear if a discouragement beam slides past them fast enough
4. make the turret and cube fizzler fx models appear and the animation play whenever the turret or cube goes through a fizzler

example for the turret laser gibs: https://youtu.be/ivKzRyw_q_8?t=13
example for the fizzler fx models: https://www.youtube.com/watch?v=95Qo_6HbSwE

**Comment by CrishNate** [comment]
About 4th:
I don't think it is worth it. I kinda like how portal originaly do it. Also it will be pretty hard to do :P

**Comment by DahMario** [comment]
it could be an option to have it on or off, i just think it's cooler with the laser gibs and fizzler fx models

**Comment by Fennecai** [comment]
Dahmario is actually right, Crish. Portal 2 has animated models for these which could be spawned in based on a simple if statement check of the model. like, "if the model is portal_turret.mdl, then [insert fake model spawning/animating code here]"

**Comment by aperturemesa67** [comment]
Wait. Portal never had any lasers, apart from the turrets. Well, if you're talking about the original Portal, that is.
