### ISSUE TITLE
[SUGGESTION] Link Tool

### ISSUE THREAD

**Issue by JammerSunstone0783** [Fennecai/Aperture-Continued#20]
**Is your feature request related to a problem? If so, Please describe.**
No

**Describe the solution you'd like**
Add something like the link tool the original addon had before they switched to the wire method 

**Describe alternatives you've considered**
None i can think of
**Additional context**
Clicking the selected object then clicking another one to link them

**Comment by Fennecai** [comment]
Just gonna let you know i think this idea is something i should add; but isnt a high priority due to how easy it is to use wiremod's tool for the same purpose. I mean; i'll add this, but just not as soon as other things maybe.

**Comment by aperturemesa67** [comment]
I would have to disagree. The new wiremod is way too complex even for the smartest gmod issue users. It's not very easy to find a direct connectionbetween something like that found in the PeTI for example.
