### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lettuceleaff** [Fennecai/Aperture-Continued#22]
**Describe the bug**
Adhesion gel is nearly impossible to stick to, and when you do, you appear very tall.

**To Reproduce**
1. Go to 'Paint gun'.
2. Click on 'Adhesion gel'.
3. Put on wall.
4. Try to use adhesion gel.
4. See error.

**Expected behavior**
Adhesion gel should allow you to stick on it in a more consistent way.
 
**Additional information**
If you do manage to stick to the adhesion gel, your point of view is very tall.

**Comment by Fennecai** [comment]
Have you attempted to debug it yourself using [the steps described on the wiki?](https://github.com/Fennecai/Aperture-Continued/wiki/The-bug-fix-self-service-guide)

if that didnt work; let me know.

**Comment by aperturemesa67** [comment]
He is actually right. I appear to have the same problem, no matter where the gel is placed. I'll temporarily walk on a wall, then fall to the floor when there is more gel on the wall above me.

**Comment by Fennecai** [comment]
sorry i never got around to this myself but i know of somebody who is trying to fix this addon, though not really actively. the addon is no longer being maintained by me though so im closing this issue.
