### ISSUE TITLE
[BUG] Gels do not render properly.

### ISSUE THREAD

**Issue by htravis123** [Fennecai/Aperture-Continued#24]
When spraying gels with the Paint Gun, the gels appear invisible, with splotches here and there

**Steps to reproduce the behavior**
1. Start a Garry's Mod map
2. Obtain the Paint Gun
3. Spray any gel except for the Cleansing Gel
4. See that the gel noes not appear properley, but is still functional

**Expected behavior**
I expected the gels to appear properly on the surface

**Additional context**
This bug relates to the add-on's Paint Gun

**Comment by Fennecai** [comment]
holy moly, people still use this addon? Sorry- I haven't been maintaining or updating it for a while now; so this isn't going to be fixed. I've moved on to several other projects

**Comment by Pop4484** [comment]
imma try getting the Paint textures from Portal 2 and try it with them

**Comment by slambo311** [comment]
> holy moly, people still use this addon? Sorry- I haven't been maintaining or updating it for a while now; so this isn't going to be fixed. I've moved on to several other projects

You should probably start working on this again, it's a great addon. For now, I'd recommend making it so the paint gun just doesn't show up, but the code's still there so you can re-enable it later.

**Comment by Fennecai** [comment]
theres sombody else working on this (i think) but again, I am not working on this anymore. even though yes, it is a great addon, I simply cant continue work on it myself. anybody who knows how to fix it is welcome to submit a pull request though.

**Comment by slambo311** [comment]
Currently, nobody else is working on it, as far as I can tell. I would help, but I don't know much lua.

**Comment by Fennecai** [comment]
well, I do know for a fact somebody I know was trying to fix the paints. I'm not entirely certain what the status is of that though- I've kind of lost contact with the person who was doing that. I would work on this if I had any room in my day to do so but I've still got other stuff taking priority; and my gmod Lua is kind of rusty at this point.
