### ISSUE TITLE
THIS IS A SUGGESTION

### ISSUE THREAD

**Issue by LibanTheCanadian** [Fennecai/Aperture-Continued#27]
make a version where you don't have the portal gun with it coz I have my main portal gun addon but the aperture continued portal gun is messing it up

**Comment by LibanTheCanadian** [comment]
wait they stopped updating? bruh

**Comment by Fennecai** [comment]
yes. quite some time ago now. don't bruh me, it's rude. I have plenty of good reasons for ceasing development on this addon, and people behaving like you are one of them.

**Comment by LibanTheCanadian** [comment]
sorry

**Comment by LibanTheCanadian** [comment]
i did not know the world bruh was rude
