### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dmeerev** [Fennecai/Aperture-Continued#28]
**Describe the bug**
Arm panel  misses all wire links when copied with advanced duplicator 1/2

**To Reproduce**
1. Spawn panel and connect to gyroscope or any same type wiremod device.
2. copy with advanced duplicator, and paste
3. press C  on panel and select "debug" option
4.input values is "0" anytime and not the same as gyroscope
4. e.g. wire looses after copy/paste

**Expected behavior**
wire still connected between panel and wiremod ic

**Comment by Fennecai** [comment]
addon is no longer being maintained by me. please read the [the front page](https://github.com/Fennecai/Aperture-Continued#readme)
