### ISSUE TITLE
hey umm

### ISSUE THREAD

**Issue by LibanTheCanadian** [Fennecai/Aperture-Continued#29]
hey umm in #27 I said sorry and I did not know bruh was a mean word I saw that you did not reply so I want to let you know that I'm sorry and I hope you can forgive me

**Comment by Fennecai** [comment]
its fine man; mistakes happen. plus i was probably dealing with some stuff emotionally when i reacted that way; so i might have taken it the wrong way myself. i appreciate the apology. thank you. just didn't have time to reply

**Comment by LibanTheCanadian** [comment]
Just want to Let you know I saw your message the next day. sorry for not responding lol. looking back at these old messages takes me back to when my days were less stressful. but C'est la vie. Since its also around Christmas time i would like to Let you Know Marry Christmas. I hope you are having a good Christmas so far, you seem like a chill and cool guy.

Best Regards,
LibanTheCanadian (Formerly epicGamingA)

**Comment by Fennecai** [comment]
Thank you very much for the Christmas Greeting and compliment. :) I hope you have a very good christmas too.
