### ISSUE TITLE
[BUG] Gel textures missing

### ISSUE THREAD

**Issue by Gman12345678901** [Fennecai/Aperture-Continued#30]
**Describe the bug**
The gel splat doesn't appear.
**To Reproduce**
1. Use any gel
2. see that nothing appears

**Expected behavior**
The gel should appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/123753800/215122713-74d53f27-3469-41cf-9227-05146170de2c.png)

**Comment by Gman12345678901** [comment]
wait

**Comment by Fennecai** [comment]
addon is no longer being maintained by me. please read the [the front page](https://github.com/Fennecai/Aperture-Continued#readme)
